# Pandas Applying Functions (`apply()`)

## What is `apply()`?

`apply()` lets you run your own Python function on every value (or row) in a DataFrame.

Think of it as:

DataFrame → My Function → New Values

---

## Why use it?

Use `apply()` when Pandas doesn't already have a built-in function.

Common examples:

- Increase salaries by 5%
- Assign risk scores
- Categorize customers
- Create fraud flags
- Clean or transform data

---

## Example

```python
def projected_salary(salary):
    return salary * 1.05

df['salary_next_year'] = df['salary_year_avg'].apply(projected_salary)
```

### What's happening?

1. Create a function.
2. Pass the function to `.apply()`.
3. Pandas runs it for every salary.
4. Save the results into a new column.

---

## Remember

- **Function** = defines the logic.
- **`apply()`** = runs that logic on every value automatically.
- Similar to a `for` loop, but Pandas handles the looping for you.

In [22]:
# Importing Libraries
import pandas as pd                              # Pandas: work with and analyze tabular data
from datasets import load_dataset               # Hugging Face: load the job postings dataset
import matplotlib.pyplot as plt                 # Matplotlib: create charts and visualizations


# Loading Data
dataset = load_dataset('lukebarousse/data_jobs') # Download/load Luke's job dataset
df = dataset['train'].to_pandas()                # Convert the dataset into a Pandas DataFrame


# Data Cleanup
df['job_posted_date'] = pd.to_datetime(
    df['job_posted_date']
)

In [23]:
# Select ONLY rows where 'salary_year_avg' is NOT missing (not NaN)
df[
    pd.notna(df['salary_year_avg'])      # Returns True for rows with a real salary
]['salary_year_avg']                     # Display only the salary_year_avg column

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [24]:
help(df.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None, args=(), by_row: "Literal[False, 'compat']" = 'compat', engine: "Callable | None | Literal['python', 'numba']" = None, engine_kwargs: 'dict[str, bool] | None' = None, **kwargs) method of pandas.DataFrame instance
    Apply a function along an axis of the DataFrame.

    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument. The return type of the applied
    function is inferred based on the first computed result obtained after
    applying the function to a Series object.

    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:

        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.

    raw : bool, default False
        Determines if row or column is passed as a Series or ndarray object:

        * ``False`` : passes each row or column as a Series to the
          function.
        * ``True`` : the passed function will receive ndarray objects
          instead.
          If you are just applying a NumPy reduction function this will
          achieve much better performance.

     .. note::

            When ``raw=True``, the result dtype is inferred from the **first**
            returned value.

    result_type : {'expand', 'reduce', 'broadcast', None}, default None
        These only act when ``axis=1`` (columns):

        * 'expand' : list-like results will be turned into columns.
        * 'reduce' : returns a Series if possible rather than expanding
          list-like results. This is the opposite of 'expand'.
        * 'broadcast' : results will be broadcast to the original shape
          of the DataFrame, the original index and columns will be
          retained.

        The default behaviour (None) depends on the return value of the
        applied function: list-like results will be returned as a Series
        of those. However if the apply function returns a Series these
        are expanded to columns.
    args : tuple
        Positional arguments to pass to `func` in addition to the
        array/series.
    by_row : False or "compat", default "compat"
        Only has an effect when ``func`` is a listlike or dictlike of funcs
        and the func isn't a string.
        If "compat", will if possible first translate the func into pandas
        methods (e.g. ``Series().apply(np.sum)`` will be translated to
        ``Series().sum()``). If that doesn't work, will try call to apply again with
        ``by_row=True`` and if that fails, will call apply again with
        ``by_row=False`` (backward compatible).
        If False, the funcs will be passed the whole Series at once.

        .. versionadded:: 2.1.0

    engine : decorator or {'python', 'numba'}, optional
        Choose the execution engine to use. If not provided the function
        will be executed by the regular Python interpreter.

        Other options include JIT compilers such Numba and Bodo, which in some
        cases can speed up the execution. To use an executor you can provide
        the decorators ``numba.jit``, ``numba.njit`` or ``bodo.jit``. You can
        also provide the decorator with parameters, like ``numba.jit(nogit=True)``.

        Not all functions can be executed with all execution engines. In general,
        JIT compilers will require type stability in the function (no variable
        should change data type during the execution). And not all pandas and
        NumPy APIs are supported. Check the engine documentation [1]_ and [2]_
        for limitations.

        .. warning::

            String parameters will stop being supported in a future pandas version.

        .. versionadded:: 2.2.0

    engine_kwargs : dict
        Pass keyword arguments to the engine.
        This is currently only used by the numba engine,
        see the documentation for the engine argument for more information.

    **kwargs
        Additional keyword arguments to pass as keywords arguments to
        `func`.

    Returns
    -------
    Series or DataFrame
        Result of applying ``func`` along the given axis of the
        DataFrame.

    See Also
    --------
    DataFrame.map: For elementwise operations.
    DataFrame.aggregate: Only perform aggregating type operations.
    DataFrame.transform: Only perform transforming type operations.

    Notes
    -----
    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    References
    ----------
    .. [1] `Numba documentation
            <https://numba.readthedocs.io/en/stable/index.html>`_
    .. [2] `Bodo documentation
            <https://docs.bodo.ai/latest/>`/

    Examples
    --------
    >>> df = pd.DataFrame([[4, 9]] * 3, columns=["A", "B"])
    >>> df
       A  B
    0  4  9
    1  4  9
    2  4  9

    Using a numpy universal function (in this case the same as
    ``np.sqrt(df)``):

    >>> df.apply(np.sqrt)
         A    B
    0  2.0  3.0
    1  2.0  3.0
    2  2.0  3.0

    Using a reducing function on either axis

    >>> df.apply(np.sum, axis=0)
    A    12
    B    27
    dtype: int64

    >>> df.apply(np.sum, axis=1)
    0    13
    1    13
    2    13
    dtype: int64

    Returning a list-like will result in a Series

    >>> df.apply(lambda x: [1, 2], axis=1)
    0    [1, 2]
    1    [1, 2]
    2    [1, 2]
    dtype: object

    Passing ``result_type='expand'`` will expand list-like results
    to columns of a Dataframe

    >>> df.apply(lambda x: [1, 2], axis=1, result_type="expand")
       0  1
    0  1  2
    1  1  2
    2  1  2

    Returning a Series inside the function is similar to passing
    ``result_type='expand'``. The resulting column names
    will be the Series index.

    >>> df.apply(lambda x: pd.Series([1, 2], index=["foo", "bar"]), axis=1)
       foo  bar
    0    1    2
    1    1    2
    2    1    2

    Passing ``result_type='broadcast'`` will ensure the same shape
    result, whether list-like or scalar is returned by the function,
    and broadcast it along the axis. The resulting column names will
    be the originals.

    >>> df.apply(lambda x: [1, 2], axis=1, result_type="broadcast")
       A  B
    0  1  2
    1  1  2
    2  1  2

    Advanced users can speed up their code by using a Just-in-time (JIT) compiler
    with ``apply``. The main JIT compilers available for pandas are Numba and Bodo.
    In general, JIT compilation is only possible when the function passed to
    ``apply`` has type stability (variables in the function do not change their
    type during the execution).

    >>> import bodo  # doctest: +SKIP
    >>> df.apply(lambda x: x.A + x.B, axis=1, engine=bodo.jit)  # doctest: +SKIP

    Note that JIT compilation is only recommended for functions that take a
    significant amount of time to run. Fast functions are unlikely to run faster
    with JIT compilation.

In [25]:
# Create a NEW independent DataFrame containing only rows with a valid salary.
# .copy() makes a separate copy so we can safely modify it
# (avoids Pandas' SettingWithCopyWarning).
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

# Define a custom Python function
# Input: one salary value
# Output: salary increased by 3%
def projected_salary(salary):
    return salary * 1.03

# Create a NEW column called 'salary_year_inflated'
# Apply the function to every value in the salary_year_avg column
df_salary['salary_year_inflated'] = (
    df_salary['salary_year_avg'].apply(projected_salary)
)

# Display only the original salary and the new projected salary columns
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [26]:
# Create (or overwrite) a new column with projected salaries
df_salary['salary_year_inflated'] = (

    # Select the salary column
    df_salary['salary_year_avg']

    # Apply a one-line (lambda) function to every salary
    .apply(
        lambda salary: salary * 1.03
        # lambda = create a quick one-line function
        # salary = the current salary value being processed
        # salary * 1.03 = increase the salary by 3%
    )
)

# Display only the original salary and the projected salary
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [27]:
type(df['job_skills'][0])

float

In [28]:
# Import the ast module for converting list-like strings into real Python lists
import ast

# Find the first non-missing value in the job_skills column
first_skills_value = df['job_skills'].dropna().iloc[0]

# Convert the string representation into a real Python list
skills_list = ast.literal_eval(first_skills_value)

# Display the converted list
skills_list

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [29]:
type(df['job_skills'][0 ])

float

In [30]:
df['job_skills'].head(10)

0                                                  NaN
1    ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2    ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3    ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4    ['bash', 'python', 'oracle', 'aws', 'ansible',...
5                             ['python', 'sql', 'gcp']
6    ['sql', 'python', 'java', 'sql server', 'gcp',...
7    ['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...
8                  ['excel', 'powerpoint', 'power bi']
9    ['sql', 'python', 'r', 'mongodb', 'mongodb', '...
Name: job_skills, dtype: str

In [31]:
df['job_skills'].first_valid_index()

1

In [32]:
type(df['job_skills'][18])

str

In [34]:

# Apply a function to every value in the 'job_skills' column.
df['job_skills'] = df['job_skills'].apply(

    # Lambda = a one-line anonymous function.
    lambda skill_list:

    # If the value is NOT missing (NaN), convert the string into a real Python list.
    ast.literal_eval(skill_list)

    # Otherwise, keep the missing value (NaN) unchanged.
    if pd.notna(skill_list) else skill_list
)

# Verify that the values are now Python lists (instead of strings).
type(df['job_skills'][0])

float

In [35]:
# Function to calculate the projected salary for each row
def projected_salary(row):

    # Check whether the job title contains the word "Senior"
    if "Senior" in row['job_title_short']:

        return 1.05 * row['salary_year_avg']      # Increase salary by 5%

    else:
        return row['salary_year_avg']             # Otherwise, keep the original salary

# Apply the function to every ROW (axis=1) and create a new column
df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

# Display only these three columns
df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0              109500.0
77       Data Engineer         140000.0              140000.0
92       Data Engineer         120000.0              120000.0
100     Data Scientist         228222.0              228222.0
109       Data Analyst          89000.0               89000.0
...                ...              ...                   ...
785624   Data Engineer         139216.0              139216.0
785641   Data Engineer         150000.0              150000.0
785648  Data Scientist         221875.0              221875.0
785682  Data Scientist         157500.0              157500.0
785692  Data Scientist         157500.0              157500.0

[22003 rows x 3 columns]